### ISSUE TITLE
task pooling

### ISSUE THREAD

**Issue by grindhold** [OParl/validator#19]
if the system recognizes, that two individuals requested a validation of the same endpoint, it should just do the validation once and send all those who requested a validation of that endpoint the result.

please be aware that the currently running validation should not be taken into account for this pooling-operation. it could be, that a person requests a validation because of a bug that he fixed. in case the current validation has been started before the bugfix on the endpoint has been deployed, the tester may receive misleading results. we should avoid this.

**Comment by eFrane** [comment]
This is a very important feature. However, it refers to the OParl/dev-website-Integration of the validator. Could you please add the issue there?
